unique_ids:
  assets:
    standard-page.html: YUX2XKIWOPVZSOLP2WMQMVBQCINAHBGI
    theme.css: SMPLAYY22XZ3XLUKU4L3TTGFQMTH44SN
  forms:
    Form1: ZDYNYGVHB2FXLKJF4RK2ZTUEU3VZVR2N
  modules: {}
  scripts: {}
  server_modules: {}
